### ISSUE TITLE
Pulling the price without screenshot

### ISSUE THREAD

**Issue by ghost** [Hecto-r/Albion-Price-Calculator#1]
Have you considered any options to pull the price via copy/paste by utilize the "Price" portion of the sell gump?

![image](https://user-images.githubusercontent.com/39036177/88621184-05704080-d05d-11ea-96ff-5f4157345cf6.png)

**Comment by Hecto-r** [comment]
Nothing came to mind that I thought would be possible to copy/paste the text. If someone knows a way to do it without interfering with the game for the user then I would definitely scratch the OCR.

Also, grabbing the price from there wont include the taxes.
