### ISSUE TITLE
Does final price include the 1.5% setup fee?

### ISSUE THREAD

**Issue by ghost** [Hecto-r/Albion-Price-Calculator#2]

**Comment by Hecto-r** [comment]
The final price that is used is the last number labeled "Total" correct me if I'm wrong, but that is the price after the 2 taxes have been deducted.
![11](https://user-images.githubusercontent.com/45679596/88682328-67ee2e80-d0a7-11ea-9ae7-9fa384f46b20.PNG)

**Comment by Hecto-r** [comment]
nvm the 1.5% isnt being calculated thank you for that I will push a hotfix later today.

**Comment by Hecto-r** [comment]
new release now includes the setup fee
